### ISSUE TITLE
[EPIC] CURD backend implementation

### ISSUE THREAD

**Issue by Artic13** [CHCTS-Microservices/TimeTracker#13]
- [x] #14
- [x] #15
- [x] #16
- [x] #17

**Comment by Artic13** [comment]
This epic was delayed by some time due to the cloud database Vendor selection. Several decisions impacted this epic.

- [ ] https://canberramedical.atlassian.net/wiki/spaces/SD/pages/12484610
- [ ] https://canberramedical.atlassian.net/wiki/spaces/SD/pages/14843979
- [ ] https://canberramedical.atlassian.net/wiki/spaces/SD/pages/14811711
- [ ] https://canberramedical.atlassian.net/wiki/spaces/SD/pages/25034753

The risks are discussed in the Risk logs
