### ISSUE TITLE
[EPIC] Main Page

### ISSUE THREAD

**Issue by hisnameisjoseph** [CHCTS-Microservices/TimeTracker#22]
- [ ] Side Panel and associated components
- [ ] Create Activity Window - Form
- [ ] Main Page Placeholder viewer

**Comment by Artic13** [comment]
Hey, hows the work going?
